import type { WordPack } from './types'

export const wordPacks: WordPack[] = [
  {
    id: 'table-talk',
    name: 'Table Talk',
    description: 'The everyday stuff hiding in plain sight.',
    tone: 'coral',
    stamp: 'TT',
    pairs: [
      { civilian: 'Coffee', undercover: 'Tea' },
      { civilian: 'Shower', undercover: 'Bath' },
      { civilian: 'Pillow', undercover: 'Blanket' },
      { civilian: 'Key', undercover: 'Lock' },
      { civilian: 'Window', undercover: 'Door' },
      { civilian: 'Text', undercover: 'Call' },
      { civilian: 'Wallet', undercover: 'Purse' },
      { civilian: 'Elevator', undercover: 'Escalator' },
      { civilian: 'Pen', undercover: 'Pencil' },
      { civilian: 'Candle', undercover: 'Lamp' },
      { civilian: 'Sock', undercover: 'Glove' },
      { civilian: 'Mirror', undercover: 'Camera' },
      { civilian: 'Couch', undercover: 'Bed' },
      { civilian: 'Clock', undercover: 'Watch' },
      { civilian: 'Notebook', undercover: 'Diary' },
      { civilian: 'Soap', undercover: 'Shampoo' },
      { civilian: 'Backpack', undercover: 'Suitcase' },
      { civilian: 'Umbrella', undercover: 'Raincoat' },
      { civilian: 'Fridge', undercover: 'Freezer' },
      { civilian: 'Fork', undercover: 'Spoon' },
    ],
  },
  {
    id: 'snack-attack',
    name: 'Snack Attack',
    description: 'Cravings, courses, and suspicious condiments.',
    tone: 'yellow',
    stamp: 'SA',
    pairs: [
      { civilian: 'Burger', undercover: 'Sandwich' },
      { civilian: 'Brownie', undercover: 'Cookie' },
      { civilian: 'Lemon', undercover: 'Lime' },
      { civilian: 'Pancake', undercover: 'Waffle' },
      { civilian: 'Ketchup', undercover: 'Mustard' },
      { civilian: 'Pasta', undercover: 'Noodles' },
      { civilian: 'Ice cream', undercover: 'Gelato' },
      { civilian: 'Muffin', undercover: 'Cupcake' },
      { civilian: 'Smoothie', undercover: 'Milkshake' },
      { civilian: 'Popcorn', undercover: 'Chips' },
      { civilian: 'Soup', undercover: 'Stew' },
      { civilian: 'Taco', undercover: 'Burrito' },
      { civilian: 'Donut', undercover: 'Bagel' },
      { civilian: 'Sushi', undercover: 'Sashimi' },
      { civilian: 'Peach', undercover: 'Apricot' },
      { civilian: 'Cereal', undercover: 'Granola' },
      { civilian: 'Espresso', undercover: 'Latte' },
      { civilian: 'Pie', undercover: 'Tart' },
      { civilian: 'Honey', undercover: 'Syrup' },
      { civilian: 'Cheese', undercover: 'Butter' },
    ],
  },
  {
    id: 'out-there',
    name: 'Out There',
    description: 'Places worth a trip and places to get lost.',
    tone: 'cyan',
    stamp: 'OT',
    pairs: [
      { civilian: 'Beach', undercover: 'Pool' },
      { civilian: 'Hotel', undercover: 'Hostel' },
      { civilian: 'Airport', undercover: 'Train station' },
      { civilian: 'Museum', undercover: 'Gallery' },
      { civilian: 'Zoo', undercover: 'Aquarium' },
      { civilian: 'City', undercover: 'Village' },
      { civilian: 'Castle', undercover: 'Palace' },
      { civilian: 'Park', undercover: 'Garden' },
      { civilian: 'Bridge', undercover: 'Tunnel' },
      { civilian: 'Cafe', undercover: 'Restaurant' },
      { civilian: 'Island', undercover: 'Peninsula' },
      { civilian: 'Harbor', undercover: 'Marina' },
      { civilian: 'Cinema', undercover: 'Theater' },
      { civilian: 'Library', undercover: 'Bookstore' },
      { civilian: 'Stadium', undercover: 'Arena' },
      { civilian: 'Mountain', undercover: 'Hill' },
      { civilian: 'River', undercover: 'Canal' },
      { civilian: 'Subway', undercover: 'Bus' },
      { civilian: 'Campsite', undercover: 'Cabin' },
      { civilian: 'Market', undercover: 'Mall' },
    ],
  },
  {
    id: 'wild-things',
    name: 'Wild Things',
    description: 'Claws, wings, weather, and the great outdoors.',
    tone: 'green',
    stamp: 'WT',
    pairs: [
      { civilian: 'Lion', undercover: 'Tiger' },
      { civilian: 'Shark', undercover: 'Dolphin' },
      { civilian: 'Bee', undercover: 'Wasp' },
      { civilian: 'Frog', undercover: 'Toad' },
      { civilian: 'Crocodile', undercover: 'Alligator' },
      { civilian: 'Crow', undercover: 'Raven' },
      { civilian: 'Butterfly', undercover: 'Moth' },
      { civilian: 'Turtle', undercover: 'Tortoise' },
      { civilian: 'Rabbit', undercover: 'Hare' },
      { civilian: 'Lizard', undercover: 'Gecko' },
      { civilian: 'Seal', undercover: 'Walrus' },
      { civilian: 'Horse', undercover: 'Donkey' },
      { civilian: 'Wolf', undercover: 'Fox' },
      { civilian: 'Eagle', undercover: 'Hawk' },
      { civilian: 'Octopus', undercover: 'Squid' },
      { civilian: 'Ant', undercover: 'Termite' },
      { civilian: 'Cactus', undercover: 'Succulent' },
      { civilian: 'Rose', undercover: 'Tulip' },
      { civilian: 'Pine', undercover: 'Palm' },
      { civilian: 'Thunder', undercover: 'Lightning' },
    ],
  },
  {
    id: 'screen-time',
    name: 'Screen Time',
    description: 'Big scenes, tiny screens, and main-character energy.',
    tone: 'pink',
    stamp: 'ST',
    pairs: [
      { civilian: 'Movie', undercover: 'Series' },
      { civilian: 'Hero', undercover: 'Villain' },
      { civilian: 'Director', undercover: 'Producer' },
      { civilian: 'Sequel', undercover: 'Prequel' },
      { civilian: 'Cinema', undercover: 'Streaming' },
      { civilian: 'Actor', undercover: 'Stunt double' },
      { civilian: 'Comedy', undercover: 'Satire' },
      { civilian: 'Podcast', undercover: 'Radio' },
      { civilian: 'Pop', undercover: 'Rock' },
      { civilian: 'DJ', undercover: 'Band' },
      { civilian: 'Camera', undercover: 'Microphone' },
      { civilian: 'Script', undercover: 'Novel' },
      { civilian: 'Animation', undercover: 'Cartoon' },
      { civilian: 'Reality show', undercover: 'Documentary' },
      { civilian: 'Award', undercover: 'Trophy' },
      { civilian: 'Stage', undercover: 'Screen' },
      { civilian: 'Rehearsal', undercover: 'Audition' },
      { civilian: 'Trailer', undercover: 'Teaser' },
      { civilian: 'Chorus', undercover: 'Verse' },
      { civilian: 'Celebrity', undercover: 'Influencer' },
    ],
  },
  {
    id: 'brainy-bunch',
    name: 'Brainy Bunch',
    description: 'School-night knowledge with tricky neighbors.',
    tone: 'blue',
    stamp: 'BB',
    pairs: [
      { civilian: 'Planet', undercover: 'Star' },
      { civilian: 'Atom', undercover: 'Molecule' },
      { civilian: 'Virus', undercover: 'Bacteria' },
      { civilian: 'Circle', undercover: 'Sphere' },
      { civilian: 'History', undercover: 'Geography' },
      { civilian: 'Algebra', undercover: 'Geometry' },
      { civilian: 'Volcano', undercover: 'Earthquake' },
      { civilian: 'Telescope', undercover: 'Microscope' },
      { civilian: 'Oxygen', undercover: 'Hydrogen' },
      { civilian: 'Map', undercover: 'Compass' },
      { civilian: 'Fraction', undercover: 'Decimal' },
      { civilian: 'Poem', undercover: 'Essay' },
      { civilian: 'Democracy', undercover: 'Monarchy' },
      { civilian: 'Magnet', undercover: 'Gravity' },
      { civilian: 'Fossil', undercover: 'Bone' },
      { civilian: 'Laboratory', undercover: 'Classroom' },
      { civilian: 'Theory', undercover: 'Hypothesis' },
      { civilian: 'Language', undercover: 'Dialect' },
      { civilian: 'Memory', undercover: 'Dream' },
      { civilian: 'Inventor', undercover: 'Explorer' },
    ],
  },
  {
    id: 'game-night',
    name: 'Game Night',
    description: 'Competition, controllers, and questionable luck.',
    tone: 'orange',
    stamp: 'GN',
    pairs: [
      { civilian: 'Chess', undercover: 'Checkers' },
      { civilian: 'Poker', undercover: 'Blackjack' },
      { civilian: 'Soccer', undercover: 'Rugby' },
      { civilian: 'Tennis', undercover: 'Badminton' },
      { civilian: 'Bowling', undercover: 'Darts' },
      { civilian: 'Hide and seek', undercover: 'Tag' },
      { civilian: 'Dice', undercover: 'Cards' },
      { civilian: 'Goal', undercover: 'Basket' },
      { civilian: 'Referee', undercover: 'Coach' },
      { civilian: 'Race', undercover: 'Marathon' },
      { civilian: 'Trophy', undercover: 'Medal' },
      { civilian: 'Puzzle', undercover: 'Riddle' },
      { civilian: 'Board game', undercover: 'Card game' },
      { civilian: 'Jump', undercover: 'Roll' },
      { civilian: 'Team', undercover: 'Player' },
      { civilian: 'Controller', undercover: 'Keyboard' },
      { civilian: 'Quest', undercover: 'Mission' },
      { civilian: 'Level', undercover: 'Round' },
      { civilian: 'Winner', undercover: 'Champion' },
      { civilian: 'Strategy', undercover: 'Luck' },
    ],
  },
  {
    id: 'night-shift',
    name: 'Night Shift',
    description: 'Late plans, loose lips, and one more round.',
    tone: 'violet',
    stamp: 'NS',
    pairs: [
      { civilian: 'Party', undercover: 'Club' },
      { civilian: 'Cocktail', undercover: 'Mocktail' },
      { civilian: 'Date', undercover: 'Anniversary' },
      { civilian: 'Whisper', undercover: 'Secret' },
      { civilian: 'Pajamas', undercover: 'Robe' },
      { civilian: 'Moon', undercover: 'Streetlight' },
      { civilian: 'Midnight', undercover: 'Dawn' },
      { civilian: 'Dance', undercover: 'Karaoke' },
      { civilian: 'Perfume', undercover: 'Cologne' },
      { civilian: 'Tattoo', undercover: 'Piercing' },
      { civilian: 'Flirt', undercover: 'Compliment' },
      { civilian: 'Wedding', undercover: 'Honeymoon' },
      { civilian: 'Bar', undercover: 'Pub' },
      { civilian: 'Champagne', undercover: 'Prosecco' },
      { civilian: 'Truth', undercover: 'Dare' },
      { civilian: 'Crush', undercover: 'Ex' },
      { civilian: 'Kiss', undercover: 'Hug' },
      { civilian: 'Limo', undercover: 'Taxi' },
      { civilian: 'Balcony', undercover: 'Rooftop' },
      { civilian: 'Hangover', undercover: 'Jet lag' },
    ],
  },
]

export const defaultPackIds = ['table-talk', 'snack-attack', 'out-there']